version: '3.9'

services:
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile # O Dockerfile deve estar em ./services/auth/
    ports:
      - "${AUTH_PORT:-3001}:3001"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - backend

  users-service:
    build:
      context: ./services/users
      dockerfile: Dockerfile # O Dockerfile deve estar em ./services/users/
    ports:
      - "${USERS_PORT:-3002}:3002"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - backend

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile # O Dockerfile deve estar em ./gateway/
    ports:
      - "${GATEWAY_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - auth-service
      - users-service
    networks:
      - backend

  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:
  elastic_data:

networks:
  backend:
